#263:
    - current_ids() is a property now
    - get_items(), get_players(), get_rools() property to
    - last is added to BaseTool - is available to Bag
    - clear() now clear last
    - pull() is renamed to pop() in Steps class
    - result of pop() is added to last
    - last_id property added in to tools
    - by_id() is added to get item from current by id
    - test all
    - check.py changes
    - docs and readme changes
    - ->